-- Multi-entity VHDL example
-- This demonstrates vhd2vl's support for files containing multiple entities
-- Useful for files generated by tools like FloPoCo

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- First entity: Simple register
entity simple_reg is
  port (
    clk : in std_logic;
    rst : in std_logic;
    d : in std_logic_vector(7 downto 0);
    q : out std_logic_vector(7 downto 0)
  );
end entity simple_reg;

architecture rtl of simple_reg is
begin
  process(clk, rst)
  begin
    if rst = '1' then
      q <= (others => '0');
    elsif rising_edge(clk) then
      q <= d;
    end if;
  end process;
end architecture rtl;

-- Second entity: Simple adder
entity simple_adder is
  port (
    a : in std_logic_vector(7 downto 0);
    b : in std_logic_vector(7 downto 0);
    sum : out std_logic_vector(8 downto 0)
  );
end entity simple_adder;

architecture rtl of simple_adder is
begin
  sum <= std_logic_vector(resize(unsigned(a), 9) + resize(unsigned(b), 9));
end architecture rtl;
